package com.llanox.chat.persistence.entities;




/**
 * ChatUsers generated by hbm2java
 */
public class ChatUser  implements java.io.Serializable {

   
	private static final long serialVersionUID = 4521343911052669500L;
	public static final String ROLE_TALKER="TALKER";
	public static final String ROLE_ADMIN="ADMIN";
	
	
	 private Long id;
     private String nickName;
     private String emailUser;
     private String role;

    public ChatUser() {
    }

	

   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getEmailUser() {
        return this.emailUser;
    }
    
    public void setEmailUser(String userSession) {
        this.emailUser = userSession;
    }


	public void setRole(String role) {
		this.role = role;
	}


	public String getRole() {
		return role;
	}

	public String toString(){
		
		return nickName;
		
	}



}



